{% set version = "8.1.5" %}

package:
  name: md-toc
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/md_toc/md_toc-{{ version }}.tar.gz
  sha256: 6260a0e69f6055bd795a243f23a834f27574bda97a2179e3507dec608dc6d67b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - md_toc = md_toc.__main__:main

requirements:
  host:
    - python >=3.6,<4.0
    - pip
  run:
    - python >=3.6,<4.0
    - setuptools
    - fpyutils >=2.1,<3

test:
  imports:
    - md_toc
  commands:
    - pip check
    - md_toc --help
  requires:
    - pip

about:
  home: https://github.com/frnmst/md-toc
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: An utility that is able to generate a table of contents for a markdown file

extra:
  recipe-maintainers:
    - ocefpaf
