{% set version = "8.0.1" %}

package:
  name: md-toc
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/md_toc/md_toc-{{ version }}.tar.gz
  sha256: 53056eadb11c79f581090ecd94d6d6f0c9e6d6ed68225b54470c0cff97b8f257

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - md_toc = md_toc.__main__:main

requirements:
  host:
    - python >=3.5,<4
    - pip
  run:
    - python >=3.5,<4
    - setuptools
    - fpyutils >=2.0,<2.1

test:
  imports:
    - md_toc
  commands:
    - pip check
    - md_toc --help
  requires:
    - pip

about:
  home: https://github.com/frnmst/md-toc
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: An utility that is able to generate a table of contents for a markdown file

extra:
  recipe-maintainers:
    - ocefpaf
