{% set name = "md-toc" %}
{% set version = "8.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/md_toc-{{ version }}.tar.gz
  sha256: a0f5d087e8e0229855f4e4d75003dd90c454e9d4959b54a887f52b2f27f1ed8f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - md_toc = md_toc.__main__:main

requirements:
  host:
    - python >=3.6,<4.0
    - pip
  run:
    - python >=3.6,<4.0
    - fpyutils >=3.0.1,<4
    - importlib-metadata >=1.0
    - setuptools

test:
  imports:
    - md_toc
  commands:
    - pip check
    - md_toc --help
  requires:
    - pip

about:
  home: https://github.com/frnmst/md-toc
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: An utility that is able to generate a table of contents for a markdown file

extra:
  recipe-maintainers:
    - ocefpaf
