{% set name = "md-toc" %}
{% set version = "9.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/md_toc-{{ version }}.tar.gz
  sha256: d66b66228d4dcd58601b06e3a88a404623e9a0e90c1bece1e707cdf0e95aa28b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - md_toc = md_toc.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - fpyutils >=4.0.1

test:
  imports:
    - md_toc
  commands:
    - pip check
    - md_toc --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/frnmst/md-toc
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: An utility that is able to generate a table of contents for a markdown file

extra:
  recipe-maintainers:
    - ocefpaf
