{% set version = "7.0.1" %}

package:
  name: md-toc
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/md_toc/md_toc-{{ version }}.tar.gz
  sha256: f259b383c20f41ced70ebc3d7bbaef4971c5a049882aa8684728edabaa033ef2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - md_toc = md_toc.__main__:main

requirements:
  host:
    - python >=3.5,<4
    - pip
  run:
    - python >=3.5,<4
    - setuptools
    - fpyutils >=1.1.0

test:
  imports:
    - md_toc
  commands:
    - pip check
    - md_toc --help
  requires:
    - pip

about:
  home: https://github.com/frnmst/md-toc
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: An utility that is able to generate a table of contents for a markdown file

extra:
  recipe-maintainers:
    - ocefpaf
