schema_version: 1

context:
  version: "9.1.0"

package:
  name: md-toc
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/m/md-toc/md_toc-${{ version }}.tar.gz
  sha256: 7914cdf1bd2d452e1b9ef95804b3a212d2463eb277c06e05ff49a11b3fd6e4d4

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - md_toc = md_toc.__main__:main

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling >=1.30
    - pip
  run:
    - python >=${{ python_min }}
    - fpyutils >=4.0.1

tests:
  - python:
      imports:
        - md_toc
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - md_toc --help

about:
  summary: Automatically generate and add an accurate table of contents to markdown files
  license: GPL-3.0-or-later
  license_file: LICENSES/GPL-3.0-or-later.txt
  homepage: https://github.com/frnmst/md-toc
  documentation: https://docs.franco.net.eu.org/md-toc/

extra:
  recipe-maintainers:
    - ocefpaf
