travis:
  secure:
    BINSTAR_TOKEN: TUfciNG6OYsYl81kbzfK+/SCa8fpAsmHjKwWaKIUrzbMxPOo6Vc3jcg7PPO7nP4RNICsbRXjI6IGFjAz7I3dqJiyYyYJFZ6NrAp8puRzgJYF7OGjPWghRo2EAZpZnuOQT3Pm+h3jY8VFgPgaUJL9AQbGm8mMrMl6AQWPkAum07IevkwRPDlwqV9OAxf/MQSynzOm98vwAn4HeE7E3QIcG96OdSA8g6vQuO3jpfNQdDGGBuaYEuDrrlrTv9+NwA9PGfqt08FxSvVXbVUgtX9v8vX8MXfDe3y7MlWiaky5MLXTESFMyPAU7tx9px06HwplFzMb4+yUGXhD28f0feT6Jwqbn98NPoM5c68AWGQgSEHO9L8q9097R6owY2p00o61zmL/PhJ1Au4AlCdRp8x4sPKG2dtPe2RO249+D322LzsGUc6VPASV8gDqbp/Dl0wlPz0CUP0M7G/Zp/Dx4guHSuYuA4/qgB62AgTnSiPL07c3uiACBZtC7Yh0i6A60m8IAi9uRh5oXs0M9XV4X57XhxeNYObAc2cydcE9rfNM5w6RTZqoxe9tvKan6pr5e4SPrtgaqsKYEoB0w48juIDciHSpJna07E1zZFoB1D9uhjWdCJcM7OfZy1OAy/B06uhEGHXAYzPbIUXJbA3AzC+QLQcr2Yk8K6uA29jarbGt7pc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: true
